export type Locality={name:string;slug:string;district:string;type:"mahalle"|"kırsal mahalle"|"sanayi bölgesi"};
const rows:[string,string,string,Locality["type"]][]=[
["İnönü","inonu","battalgazi","mahalle"],["Orduzu","orduzu","battalgazi","mahalle"],["Fırat","firat","battalgazi","mahalle"],["Çöşnük","cosnuk","battalgazi","mahalle"],["Başharık","basharik","battalgazi","mahalle"],["Kernek","kernek","battalgazi","mahalle"],["Niyazi","niyazi","battalgazi","mahalle"],["Saray","saray","battalgazi","mahalle"],["Şifa","sifa","battalgazi","mahalle"],["İskender","iskender","battalgazi","mahalle"],["Beydağı","beydagi","battalgazi","mahalle"],["Hanımınçiftliği","haniminciftligi","battalgazi","mahalle"],["Hatunsuyu","hatunsuyu","battalgazi","kırsal mahalle"],["Yaygın","yaygin","battalgazi","kırsal mahalle"],["Hasırcılar","hasircilar","battalgazi","kırsal mahalle"],["Kemerköprü","kemerkopru","battalgazi","kırsal mahalle"],["Toygar","toygar","battalgazi","kırsal mahalle"],
["Tecde","tecde","yesilyurt","mahalle"],["Çilesiz","cilesiz","yesilyurt","mahalle"],["Yakınca","yakinca","yesilyurt","mahalle"],["Bostanbaşı","bostanbasi","yesilyurt","mahalle"],["Karakavak","karakavak","yesilyurt","mahalle"],["Özalper","ozalper","yesilyurt","mahalle"],["Turgut Özal","turgut-ozal","yesilyurt","mahalle"],["Şeyh Bayram","seyh-bayram","yesilyurt","mahalle"],["Gündüzbey","gunduzbey","yesilyurt","mahalle"],["Dilek","dilek","yesilyurt","mahalle"],["Şahnahan","sahnahan","yesilyurt","kırsal mahalle"],["Konak","konak","yesilyurt","mahalle"],["Melekbaba","melekbaba","yesilyurt","mahalle"],["Koyunoğlu","koyunoglu","yesilyurt","mahalle"],["I. Organize Sanayi Bölgesi","birinci-osb","yesilyurt","sanayi bölgesi"],["II. Organize Sanayi Bölgesi","ikinci-osb","yesilyurt","sanayi bölgesi"],
["Akçadağ Merkez","akcadag-merkez","akcadag","mahalle"],["Levent","levent","akcadag","kırsal mahalle"],["Kozluca","kozluca","akcadag","kırsal mahalle"],["Ören","oren","akcadag","mahalle"],["Kürecik","kurecik","akcadag","kırsal mahalle"],["Akçadağ Mermer OSB","mermer-osb","akcadag","sanayi bölgesi"],
["Arapgir Merkez","arapgir-merkez","arapgir","mahalle"],["Onar","onar","arapgir","kırsal mahalle"],["Serge","serge","arapgir","kırsal mahalle"],["Berenge","berenge","arapgir","kırsal mahalle"],
["Arguvan Merkez","arguvan-merkez","arguvan","mahalle"],["Bozan","bozan","arguvan","kırsal mahalle"],["Çavuş","cavus","arguvan","kırsal mahalle"],["Morhamam","morhamam","arguvan","kırsal mahalle"],
["Darende Merkez","darende-merkez","darende","mahalle"],["Zaviye","zaviye","darende","mahalle"],["Balaban","balaban","darende","mahalle"],["Aşağıulupınar","asagiulupinar","darende","mahalle"],["Ayvalı","ayvali","darende","mahalle"],["Darende OSB","darende-osb","darende","sanayi bölgesi"],
["Doğanşehir Merkez","dogansehir-merkez","dogansehir","mahalle"],["Sürgü","surgu","dogansehir","mahalle"],["Polat","polat","dogansehir","mahalle"],["Erkenek","erkenek","dogansehir","mahalle"],["Kurucaova","kurucaova","dogansehir","mahalle"],
["Doğanyol Merkez","doganyol-merkez","doganyol","mahalle"],["Gökçe","gokce","doganyol","kırsal mahalle"],["İsak","isak","doganyol","kırsal mahalle"],
["Hekimhan Merkez","hekimhan-merkez","hekimhan","mahalle"],["Hasançelebi","hasancelebi","hekimhan","mahalle"],["Güzelyurt","guzelyurt","hekimhan","mahalle"],["Kocaözü","kocaozu","hekimhan","kırsal mahalle"],
["Kale Merkez","kale-merkez","kale","mahalle"],["Bentköy","bentkoy","kale","kırsal mahalle"],["İzollu","izollu","kale","kırsal mahalle"],
["Kuluncak Merkez","kuluncak-merkez","kuluncak","mahalle"],["Sofular","sofular","kuluncak","kırsal mahalle"],["Konakpınar","konakpinar","kuluncak","kırsal mahalle"],
["Pütürge Merkez","puturge-merkez","puturge","mahalle"],["Doğanyol Yolu","doganyol-yolu","puturge","kırsal mahalle"],["Tepehan","tepehan","puturge","mahalle"],["Nohutlu","nohutlu","puturge","kırsal mahalle"],
["Yazıhan Merkez","yazihan-merkez","yazihan","mahalle"],["Fethiye","fethiye","yazihan","mahalle"],["Durucasu","durucasu","yazihan","mahalle"],["Malatya Besi TDİ OSB","besi-tdi-osb","yazihan","sanayi bölgesi"],["Yazıhan Sera OSB","sera-osb","yazihan","sanayi bölgesi"]
];
export const localities:Locality[]=rows.map(([name,slug,district,type])=>({name,slug,district,type}));
export const localityByDistrict=(district:string)=>localities.filter(x=>x.district===district);
