export const services = [
  {slug:"elektrik-tesisati",title:"Elektrik Tesisatı",icon:"ϟ",short:"Sıfır tesisat, kolon hattı, pano, topraklama ve bina elektrik yenileme.",detail:"Konut, iş yeri, mağaza ve şantiyelerde elektrik altyapısını güvenlik ve kapasite ihtiyaçlarına göre planlıyor; sıfırdan kurulum, yenileme ve kontrol hizmeti veriyoruz.",bullets:["Sıfırdan daire ve bina elektrik tesisatı","Elektrik panosu ve sigorta düzenleme","Topraklama ve kaçak akım koruması","Kolon hattı ve kablo yenileme"]},
  {slug:"elektrik-ariza",title:"Elektrik Arıza",icon:"⚡",short:"Sigorta atması, kısa devre, enerji kesintisi ve hat arızalarında kontrollü müdahale.",detail:"Sürekli atan sigorta, çalışmayan hat, yanık kokusu, gerilim sorunu ve açıklanamayan elektrik kesintilerinde arıza kaynağını sistemli biçimde araştırıyoruz.",bullets:["Sigorta ve kaçak akım arızası","Kısa devre ve kopuk hat tespiti","Isınan priz ve kablo kontrolü","Daire içi enerji kesintisi"]},
  {slug:"priz-tamiri",title:"Priz Tamiri ve Montajı",icon:"▣",short:"Çalışmayan, gevşeyen veya ısınan prizlerin yenilenmesi ve yeni priz hattı.",detail:"Gevşek, kararmış, kıvılcım yapan veya çalışmayan prizleri; bağlı hat, kablo ve koruma elemanlarıyla birlikte kontrol ediyoruz. İhtiyaca göre yeni priz noktaları oluşturuyoruz.",bullets:["Yanmış ve gevşek priz değişimi","Yeni priz hattı çekimi","USB ve tezgâh üstü priz montajı","Topraklama kontrolü"]},
  {slug:"avize-aydinlatma",title:"Avize ve Aydınlatma",icon:"✦",short:"Avize, aplik, spot, LED ürün seçimi, satışı ve güvenli montajı.",detail:"Mekânın ölçüsü, tavan yüksekliği ve kullanım amacına uygun avize ve aydınlatma ürünlerinin seçimi, tedariği ve montajını birlikte çözüyoruz.",bullets:["Avize ve sarkıt montajı","LED, spot ve şerit LED uygulaması","Bahçe ve cephe aydınlatması","Aydınlatma arızası ve sürücü değişimi"]},
  {slug:"sihhi-tesisat",title:"Sıhhi Tesisat",icon:"◉",short:"Temiz ve atık su hatları, boru yenileme, armatür ve vitrifiye montajı.",detail:"Temiz su ve atık su tesisatı, boru yenileme, musluk, lavabo, klozet, duş ve mutfak bağlantıları için uygulama ve onarım sunuyoruz.",bullets:["Temiz ve pis su tesisatı","Mutfak ve banyo tesisat yenileme","Musluk, batarya ve vitrifiye montajı","Donmuş veya hasarlı boru onarımı"]},
  {slug:"su-kacagi-tespiti",title:"Su Kaçağı Tespiti",icon:"⌕",short:"Duvar, zemin ve tesisat hatlarındaki gizli su kaçaklarının araştırılması.",detail:"Artan su faturası, nem, kabaran boya ve alt kata sızıntı gibi belirtilerde kaçak ihtimalini değerlendiriyor, mümkün olan en sınırlı müdahaleyi planlıyoruz.",bullets:["Temiz su hattı kaçak kontrolü","Gider ve bağlantı sızıntıları","Sayaç üzerinden ön kontrol","Noktasal onarım planlaması"]},
  {slug:"tikali-gider-acma",title:"Tıkalı Gider Açma",icon:"↯",short:"Lavabo, mutfak, banyo, klozet ve ana gider tıkanıklıklarına müdahale.",detail:"Yavaş akan veya tamamen tıkanan giderlerde sorunun yerini ve nedenini değerlendirerek uygun açma ve temizlik yöntemini seçiyoruz.",bullets:["Lavabo ve eviye tıkanıklığı","Banyo ve duş gideri","Klozet ve WC hattı","Bina ana gider kontrolü"]},
  {slug:"hidrofor-tamiri",title:"Hidrofor Tamiri",icon:"↥",short:"Hidrofor, su pompası, basınç tankı ve kontrol ekipmanlarında bakım ve arıza.",detail:"Suyun üst katlara çıkmaması, basınç dalgalanması, pompanın sık devreye girmesi veya çalışmaması durumlarında hidrofor sistemini bütün olarak kontrol ediyoruz.",bullets:["Hidrofor arıza tespiti","Pompa ve motor kontrolü","Basınç şalteri ve tank bakımı","Yeni hidrofor seçimi ve montajı"]},
  {slug:"su-deposu-temizligi",title:"Su Deposu Temizliği",icon:"◇",short:"Bina ve işletme depolarında boşaltma, tortu temizliği ve hijyen uygulaması.",detail:"Apartman, site ve işletme su depolarında kontrollü boşaltma, yüzey ve tortu temizliği ile hijyen odaklı bakım hizmeti veriyoruz.",bullets:["Depo boşaltma ve ön kontrol","Tortu ve yüzey temizliği","Durulama ve sistem kontrolü","Periyodik bakım planlaması"]},
  {slug:"mekanik-tesisat",title:"Mekanik Tesisat",icon:"⌁",short:"Isıtma, soğutma, havalandırma, pompa ve tesisat koordinasyonu.",detail:"Yapının ısıtma, soğutma, havalandırma ve basınçlandırma ihtiyaçlarını değerlendirerek uygulanabilir, bakımı kolay mekanik sistem çözümleri geliştiriyoruz.",bullets:["Isıtma ve tesisat hatları","Havalandırma uygulamaları","Pompa ve basınç sistemleri","Elektrik-mekanik koordinasyonu"]},
  {slug:"petek-temizligi",title:"Petek Temizliği",icon:"≋",short:"Isınmayan petekler, dolaşım sorunları ve tesisat bakım uygulamaları.",detail:"Peteklerin altının soğuk kalması, odalar arasında ısı farkı veya dolaşım problemi yaşanması halinde ısıtma tesisatını ve petekleri kontrol ediyoruz.",bullets:["Petek ve tesisat kontrolü","Dolaşım problemi değerlendirmesi","Vana ve bağlantı kontrolü","Sistem havası ve basınç kontrolü"]},
  {slug:"anahtar-teslim-insaat",title:"Anahtar Teslim İnşaat",icon:"⌂",short:"Kaba yapıdan ince işlere, elektrik ve mekanik dahil tek elden proje yönetimi.",detail:"Yeni yapı, tadilat ve dönüşüm projelerini keşif, bütçe, iş programı, ekip koordinasyonu ve teslim süreçleriyle tek merkezden yönetiyoruz.",bullets:["Kaba ve ince yapı uygulamaları","Komple daire ve iş yeri tadilatı","Elektrik ve mekanik tesisatlar","Boya, alçı, seramik ve teslim"]},
];

export const districts=[["Akçadağ","akcadag"],["Arapgir","arapgir"],["Arguvan","arguvan"],["Battalgazi","battalgazi"],["Darende","darende"],["Doğanşehir","dogansehir"],["Doğanyol","doganyol"],["Hekimhan","hekimhan"],["Kale","kale"],["Kuluncak","kuluncak"],["Pütürge","puturge"],["Yazıhan","yazihan"],["Yeşilyurt","yesilyurt"]].map(([name,slug])=>({name,slug}));

export const posts=[
  {slug:"elektrik-tesisati-yenileme-belirtileri",category:"ELEKTRİK",title:"Elektrik tesisatının yenilenmesi gerektiğini gösteren 7 işaret",excerpt:"Sık atan sigorta, ısınan priz ve yetersiz hatlar ne anlatır? Güvenli bir kontrol listesi.",reading:6},
  {slug:"priz-neden-isinir",category:"ELEKTRİK",title:"Priz neden ısınır, ne zaman değiştirilmelidir?",excerpt:"Gevşek bağlantı, aşırı yük ve eski priz mekanizmasının oluşturduğu riskleri öğrenin.",reading:5},
  {slug:"sigorta-surekli-neden-atar",category:"ELEKTRİK",title:"Sigorta sürekli neden atar?",excerpt:"Aşırı yük, kısa devre ve kaçak akım arasındaki farkı pratik belirtilerle anlayın.",reading:5},
  {slug:"su-kacagi-erken-belirtileri",category:"SIHHİ TESİSAT",title:"Gizli su kaçağı nasıl anlaşılır?",excerpt:"Kabaran boya, artan fatura ve rutubet kokusu gibi erken belirtileri gözden kaçırmayın.",reading:5},
  {slug:"lavabo-tikanikligi-neden-olur",category:"SIHHİ TESİSAT",title:"Lavabo tıkanıklığı neden tekrarlar?",excerpt:"Yağ, tortu ve yanlış boru eğiminin gider hattına etkisi hakkında temel bilgiler.",reading:4},
  {slug:"hidrofor-surekli-calisiyor",category:"MEKANİK",title:"Hidrofor neden sürekli çalışır?",excerpt:"Basınç tankı, kaçak, çekvalf ve basınç şalteri kaynaklı olası sorunlar.",reading:6},
  {slug:"peteklerin-alti-neden-soguk",category:"ISITMA",title:"Peteklerin altı neden soğuk kalır?",excerpt:"Hava, tortu ve dolaşım sorunlarını birbirinden ayırmaya yardımcı kontrol listesi.",reading:5},
  {slug:"avize-secim-rehberi",category:"AYDINLATMA",title:"Odaya göre doğru avize nasıl seçilir?",excerpt:"Salon, mutfak ve yatak odasında ölçü, renk sıcaklığı ve ışık gücü için pratik rehber.",reading:4},
  {slug:"su-deposu-ne-zaman-temizlenmeli",category:"BAKIM",title:"Su deposu ne sıklıkla temizlenmeli?",excerpt:"Tortu, koku ve renk değişimini beklemeden periyodik bakım planı oluşturmanın önemi.",reading:4},
  {slug:"ev-tadilati-nereden-baslanir",category:"İNŞAAT",title:"Ev tadilatına nereden başlanır?",excerpt:"Elektrik, su, mekanik ve ince işlerin doğru uygulama sırasını planlayın.",reading:7},
];
