import type {Metadata} from "next"; import {notFound} from "next/navigation"; import {posts} from "../../site-data"; import {SimpleHeader,Cta} from "../../hizmetler/[slug]/page";
export function generateStaticParams(){return posts.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=posts.find(x=>x.slug===slug);return p?{title:p.title,description:p.excerpt,alternates:{canonical:`/blog/${slug}`}}:{}}
const paragraphs:Record<string,string[]>={
"elektrik-tesisati-yenileme-belirtileri":["Sigortanın sık atması, prizlerde ısınma veya yanık kokusu, lambalarda sebepsiz titreme ve aynı anda birkaç cihaz çalıştığında yaşanan kesintiler tesisatın kontrol edilmesi gerektiğini gösterir.","Eski yapılarda sonradan eklenen güçlü cihazlar mevcut hat kapasitesini aşabilir. Kablo kesitleri, topraklama, kaçak akım koruması ve pano düzeni uzman tarafından birlikte değerlendirilmelidir.","Isınan prize dokunmayı, sürekli atan sigortayı daha yüksek amperli sigortayla değiştirmeyi veya açıkta kabloyu geçici bantla bırakmayı güvenli çözüm saymayın. Enerjiyi kesin ve yetkin destek alın."],
"su-kacagi-erken-belirtileri":["Su kullanmadığınız halde sayaç hareket ediyorsa, duvarda kabarma ve sararma oluşuyorsa veya kapalı bir alanda sürekli rutubet kokusu varsa gizli kaçak ihtimali vardır.","Kaçak erken bulunmadığında boya ve sıva hasarının yanında komşu bağımsız bölümlere zarar ve gereksiz su tüketimi oluşabilir. Önce gözle kontrol, sonra uygun tespit yöntemiyle noktasal müdahale planlanmalıdır.","Bütün muslukları kapatıp sayaç göstergesini not edin. Kısa süre sonra değişim varsa tesisatı kontrol ettirin."],
"avize-secim-rehberi":["Avize seçiminde yalnızca görünüşe değil odanın ölçüsüne, tavan yüksekliğine ve kullanım amacına bakın. Büyük bir salon tek merkez ışığıyla yetinmez; genel, görev ve vurgu aydınlatması birlikte düşünülmelidir.","Sıcak beyaz ışık dinlenme alanlarında, daha nötr ışık mutfak ve çalışma alanlarında tercih edilebilir. Ürünün ağırlığı ve tavan bağlantısı montaj güvenliği açısından mutlaka kontrol edilmelidir.","Masa üzeri sarkıtın yüksekliği görüşü kesmemeli; yatak odası ve koridorda parlamayı azaltan kapalı veya yayıcı yüzeyler tercih edilmelidir."],
"su-deposu-ne-zaman-temizlenmeli":["Su deposundaki tortu, yüzeylerde birikme, koku veya renk değişimi bakım ihtiyacının görünür işaretleridir. Ancak bakım için bu belirtileri beklemek doğru değildir.","Temizlik aralığı deponun malzemesine, su kaynağına, kullanım yoğunluğuna ve çevresel koşullara göre belirlenmelidir. Periyodik kontrol kaydı tutmak en sağlıklı yaklaşımdır.","İşlem; güvenli boşaltma, fiziksel temizlik, uygun hijyen uygulaması, durulama ve sistem kontrolü adımlarını kapsamalıdır."]
};
export default async function Post({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=posts.find(x=>x.slug===slug);if(!p)notFound();return <main className="inner"><SimpleHeader/><article className="article"><span>{p.category}</span><h1>{p.title}</h1><p className="intro">{p.excerpt}</p>{paragraphs[slug].map((x,i)=><section key={x}><h2>{i===0?"Hangi belirtilere dikkat edilmeli?":i===1?"Doğru yaklaşım nedir?":"Pratik öneri"}</h2><p>{x}</p></section>)}</article><Cta/></main>}
