import type {Metadata} from "next"; import {notFound} from "next/navigation"; import {posts} from "../../site-data"; import {SimpleHeader,Cta} from "../../hizmetler/[slug]/page";
export function generateStaticParams(){return posts.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=posts.find(x=>x.slug===slug);return p?{title:p.title,description:p.excerpt,alternates:{canonical:`/blog/${slug}`}}:{}}
const paragraphs:Record<string,string[]>={
"elektrik-tesisati-yenileme-belirtileri":["Sigortanın sık atması, prizlerde ısınma veya yanık kokusu, lambalarda sebepsiz titreme ve aynı anda birkaç cihaz çalıştığında yaşanan kesintiler tesisatın kontrol edilmesi gerektiğini gösterir.","Eski yapılarda sonradan eklenen güçlü cihazlar mevcut hat kapasitesini aşabilir. Kablo kesitleri, topraklama, kaçak akım koruması ve pano düzeni uzman tarafından birlikte değerlendirilmelidir.","Isınan prize dokunmayı, sürekli atan sigortayı daha yüksek amperli sigortayla değiştirmeyi veya açıkta kabloyu geçici bantla bırakmayı güvenli çözüm saymayın. Enerjiyi kesin ve yetkin destek alın."],
"su-kacagi-erken-belirtileri":["Su kullanmadığınız halde sayaç hareket ediyorsa, duvarda kabarma ve sararma oluşuyorsa veya kapalı bir alanda sürekli rutubet kokusu varsa gizli kaçak ihtimali vardır.","Kaçak erken bulunmadığında boya ve sıva hasarının yanında komşu bağımsız bölümlere zarar ve gereksiz su tüketimi oluşabilir. Önce gözle kontrol, sonra uygun tespit yöntemiyle noktasal müdahale planlanmalıdır.","Bütün muslukları kapatıp sayaç göstergesini not edin. Kısa süre sonra değişim varsa tesisatı kontrol ettirin."],
"avize-secim-rehberi":["Avize seçiminde yalnızca görünüşe değil odanın ölçüsüne, tavan yüksekliğine ve kullanım amacına bakın. Büyük bir salon tek merkez ışığıyla yetinmez; genel, görev ve vurgu aydınlatması birlikte düşünülmelidir.","Sıcak beyaz ışık dinlenme alanlarında, daha nötr ışık mutfak ve çalışma alanlarında tercih edilebilir. Ürünün ağırlığı ve tavan bağlantısı montaj güvenliği açısından mutlaka kontrol edilmelidir.","Masa üzeri sarkıtın yüksekliği görüşü kesmemeli; yatak odası ve koridorda parlamayı azaltan kapalı veya yayıcı yüzeyler tercih edilmelidir."],
"su-deposu-ne-zaman-temizlenmeli":["Su deposundaki tortu, yüzeylerde birikme, koku veya renk değişimi bakım ihtiyacının görünür işaretleridir. Ancak bakım için bu belirtileri beklemek doğru değildir.","Temizlik aralığı deponun malzemesine, su kaynağına, kullanım yoğunluğuna ve çevresel koşullara göre belirlenmelidir. Periyodik kontrol kaydı tutmak en sağlıklı yaklaşımdır.","İşlem; güvenli boşaltma, fiziksel temizlik, uygun hijyen uygulaması, durulama ve sistem kontrolü adımlarını kapsamalıdır."]
};
const longGuide=(title:string,category:string)=>[
{h:"Konuyu doğru tanımlamak",t:`${title} konusunda sağlıklı bir kararın ilk adımı ihtiyacı doğru tanımlamaktır. ${category.toLocaleLowerCase("tr-TR")} çalışmalarında görünen belirti her zaman arızanın gerçek kaynağı olmayabilir. Sorunun ne zaman başladığı, sürekli mi aralıklı mı yaşandığı, hangi cihazlar veya kullanım koşullarıyla birlikte ortaya çıktığı not edilmelidir. Daha önce yapılan onarımlar, yapının yaşı ve mevcut tesisatın malzemesi de değerlendirmeyi etkiler. Bu bilgiler ustanın kontrol sırasını oluşturmasına ve gereksiz söküm ya da parça değişiminden kaçınmasına yardımcı olur.`},
{h:"Keşif öncesinde hazırlanacak bilgiler",t:"İşin yapılacağı ilçe ve mahalle, yapı türü, yaklaşık alan, kat bilgisi ve erişim koşulları önceden paylaşılmalıdır. Arıza söz konusuysa ses, koku, ısınma, basınç değişimi, nem veya kesinti gibi belirtiler açıkça anlatılmalıdır. Yeni uygulamalarda ise kullanılacak cihaz sayısı, priz ve aydınlatma noktaları, su tüketimi, pompa kapasitesi veya beklenen kullanım yoğunluğu önemlidir. Fotoğraf, video, mevcut proje ve ölçüler ön değerlendirmeyi kolaylaştırır; ancak kapsamlı işlerde yerinde incelemenin yerini tamamen tutmaz."},
{h:"Güvenlik neden önceliklidir?",t:"Elektrik, basınçlı su, pompa, pano ve yapı işleri doğrudan can ve mal güvenliğiyle ilişkilidir. Enerji altında bağlantıya müdahale etmek, koruma elemanını devre dışı bırakmak, uygun olmayan kablo veya boru kullanmak geçici olarak çalışsa bile ciddi risk doğurabilir. Su ile elektrik tesisatının yakın olduğu banyo, mutfak, depo ve makine dairesi gibi alanlarda koordinasyon daha da önemlidir. Arıza belirtisi varken sistemi zorlamamak, güvenli biçimde kapatmak ve yetkin destek istemek en doğru yaklaşımdır."},
{h:"Doğru malzeme ve kapasite seçimi",t:"Kalıcı bir uygulama yalnızca iyi işçilikle değil, doğru kapasitede ve kullanım yerine uygun malzemeyle mümkündür. Elektrikte kablo kesiti ve koruma elemanları yüke göre; su tesisatında boru çapı ve basınç sınıfı tüketime göre seçilir. Pompa ve hidroforlarda debi, basma yüksekliği ve çalışma sıklığı birlikte hesaplanır. Sulama sistemlerinde hat uzunluğu, kot farkı ve filtreleme dikkate alınır. Gereğinden küçük ekipman sürekli zorlanır; gereğinden büyük ekipman ise maliyet ve kontrol sorunları yaratabilir."},
{h:"Uygulama sırası nasıl planlanır?",t:"Sıfırdan tesisat veya tadilat işinde disiplinler doğru sırayla ilerlemelidir. Önce söküm ve mevcut durum tespiti yapılır, ardından elektrik, temiz su, atık su ve mekanik hatların güzergâhları belirlenir. Kaba tesisat tamamlanmadan duvar ve zemin kapatılmamalıdır. Basınç, izolasyon ve elektriksel kontrollerden sonra sıva, şap, seramik, boya ve montaj aşamasına geçilir. Avize, priz, armatür ve vitrifiye gibi son ürünler yüzey işleri bittikten sonra takılır. Bu sıra, tekrar kırma ve gereksiz işçilik riskini azaltır."},
{h:"Teklifte hangi kalemler bulunmalı?",t:"Teklif yalnızca toplam rakamdan ibaret olmamalıdır. Söküm, işçilik, temel malzemeler, taşıma, erişim ekipmanı, test ve teslim gibi kalemlerin kapsamı anlaşılır şekilde belirtilmelidir. Hangi işlemlerin fiyata dahil olmadığı, keşif sırasında öngörülemeyen durumlarda nasıl hareket edileceği ve iş programının yaklaşık süresi açıklanmalıdır. Ürün seçimi müşteriye bırakılıyorsa teknik asgari özellikler yazılmalıdır. Böyle bir kapsam hem fiyatları karşılaştırmayı kolaylaştırır hem de uygulama sırasında tarafların beklentisini netleştirir."},
{h:"Sık yapılan hatalar",t:"Belirtiyi araştırmadan yalnızca görünen parçayı değiştirmek en sık yapılan hatalardan biridir. Sürekli atan sigortaya daha yüksek amper takmak, kaçak yapan boruyu uygun olmayan ekle kapatmak, pompanın basınç ayarını gelişigüzel yükseltmek veya tıkalı hattı boruya zarar verecek yöntemle açmak sorunu büyütebilir. Projesiz eklenen prizler, yetersiz topraklama, filtresiz sulama hattı ve yanlış çaplı borular da ileride arıza oluşturur. Her müdahalenin sistemin geri kalanına etkisi düşünülmelidir."},
{h:"Bakım ve periyodik kontrol",t:"Tesisatların arıza vermesini beklemek yerine düzenli kontrol edilmesi işletme ve konut güvenliğini artırır. Elektrik panolarında gevşek bağlantı, ısınma ve kirlenme; hidroforlarda basınç tankı, çekvalf ve kaçak; pompalarda ses, titreşim ve debi; sulama hatlarında filtre ve vana durumu izlenmelidir. Su depoları kullanım koşullarına göre temizlenmeli, giderlerde yavaşlama erken fark edilmelidir. Kontrol tarihlerini ve yapılan işlemleri kaydetmek tekrar eden sorunların nedenini anlamayı kolaylaştırır."},
{h:"Konut, iş yeri ve sanayi farkı",t:"Aynı hizmet başlığı farklı yapılarda farklı tasarım gerektirir. Konutta kullanıcı güvenliği, sessizlik ve estetik ön plandayken iş yerinde çalışma saatleri, müşteri dolaşımı ve kesintisiz işletme önem kazanır. Sanayi tesislerinde makine yükleri, kompanzasyon, pano seçiciliği, kablo güzergâhı ve bakım erişimi daha ayrıntılı değerlendirilir. Tarımsal alanlarda ise uzak mesafe, dış ortam, su kaynağı ve enerji kalitesi belirleyicidir. Bu nedenle hazır tek bir çözümü her yapıya uygulamak doğru değildir."},
{h:"İş bitiminde yapılacak kontroller",t:"Uygulama tamamlandığında sistem çalışıyor görünse bile teslim kontrolleri yapılmalıdır. Elektrik devreleri etiketlenmeli, priz ve aydınlatma noktaları denenmeli, koruma elemanlarının uygunluğu gözden geçirilmelidir. Su hatlarında kaçak ve basınç, giderlerde akış, pompalarda devreye girme ve durma davranışı kontrol edilir. Kullanıcıya vana, sigorta, pano, zamanlayıcı veya kontrol cihazlarının temel kullanımı anlatılmalıdır. Çalışma alanının temiz ve erişilebilir bırakılması da tamamlanmış işin parçasıdır."},
{h:"Enerji ve su verimliliği",t:"Doğru tasarlanmış tesisat yalnızca arızayı önlemez, enerji ve su tüketimini de kontrol altında tutar. Gereksiz basınçta çalışan pompa, yanlış ayarlı hidrofor, kaçak yapan rezervuar, verimsiz aydınlatma veya sürekli devrede kalan ekipman faturayı artırır. Sulama saatlerinin ve zonlarının doğru ayarlanması buharlaşma kaybını azaltabilir. Elektrik yüklerinin dengeli dağıtılması ve uygun LED ürünlerin seçilmesi de işletme maliyetine katkı sağlar. Yenileme kararında yalnızca ilk yatırım fiyatını değil, bakım kolaylığını, beklenen ömrü ve tüketim değerlerini birlikte değerlendirmek gerekir."},
{h:"Eski yapılarda yenileme yaklaşımı",t:"Eski bir yapıda tesisat yenilemek, boş bir binada sıfırdan uygulama yapmaktan farklıdır. Duvar ve zemin içindeki mevcut hatların güzergâhı her zaman projeyle uyumlu olmayabilir. Sonradan eklenen priz, boru ve cihazlar yük veya basınç dengesini değiştirmiş olabilir. Önce mevcut sistem haritalanmalı, kullanılabilecek bölümlerle tamamen yenilenmesi gereken bölümler ayrılmalıdır. Kısmi yenileme yapılacaksa yeni ve eski malzemenin bağlantı uyumu kontrol edilmeli; kapatılacak ek ve bağlantı noktaları ileride bakım yapılabilecek şekilde planlanmalıdır."},
{h:"Usta ve yüklenici seçerken",t:"Hizmet sağlayıcı seçerken yalnızca en düşük fiyatı değil, sorunu nasıl değerlendirdiğini ve kapsamı ne kadar açık anlattığını inceleyin. Keşif sırasında ölçüm ve kontrol yapmadan kesin hüküm veren, koruma elemanlarını devre dışı bırakmayı öneren veya kullanılacak malzemeyi belirtmeyen yaklaşımlar riskli olabilir. Kapsamlı işlerde elektrik, su, mekanik ve ince iş ekiplerinin kim tarafından koordine edileceği sorulmalıdır. İletişim, iş programı, çalışma alanının korunması ve teslim kontrolü de teknik uygulama kadar önemlidir. Yazılı kapsam sonradan yaşanabilecek anlaşmazlıkları azaltır."},
{h:"Malatya’da hizmet planlaması",t:"Malatya merkez ve ilçelerinde hizmet planlanırken yerleşimin uzaklığı, yol koşulları, malzeme temini ve işin aciliyeti birlikte değerlendirilir. Battalgazi ve Yeşilyurt’taki yoğun konut alanlarıyla kırsal mahalle, tarla, bağ ve sanayi bölgelerinin ihtiyaçları aynı değildir. Kırsal uygulamalarda pompa, sulama ve enerji hattı; merkezde ise daire tesisatı, priz, aydınlatma ve tadilat talepleri öne çıkabilir. Konum ve iş kapsamını teklif formunda ayrıntılı paylaşmak doğru ekip ve malzeme hazırlığını kolaylaştırır."}
];
export default async function Post({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=posts.find(x=>x.slug===slug);if(!p)notFound();const specific=paragraphs[slug]??[];const guide=longGuide(p.title,p.category);return <main className="inner"><SimpleHeader/><article className="article"><span>{p.category}</span><h1>{p.title}</h1><p className="intro">{p.excerpt}</p>{specific.map((x,i)=><section key={x}><h2>{i===0?"Belirtileri doğru okuyun":i===1?"Doğru çözüm yaklaşımı":"Pratik öneri"}</h2><p>{x}</p></section>)}{guide.map(x=><section key={x.h}><h2>{x.h}</h2><p>{x.t}</p></section>)}</article><Cta/></main>}
